/**
 * Shared helpers for the "AI Subjects" feature:
 *   - main_admin.htm   (via ai-subjects-admin.js)  → generate / review / publish
 *   - subject.htm       → course overview (student-facing)
 *   - subject-lesson.htm→ lesson workspace (student-facing)
 *
 * Firebase is initialised via getApps() dedupe — the same trick
 * university-admin.js and ai-vault-shared.js use — so importing this from
 * any page never double-initialises.
 */
import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/12.14.0/firebase-app.js";
import { getAuth } from "https://www.gstatic.com/firebasejs/12.14.0/firebase-auth.js";
import { getFirestore, doc, getDoc, collection, query, where, getDocs } from "https://www.gstatic.com/firebasejs/12.14.0/firebase-firestore.js";

const firebaseConfig = {
  apiKey: "AIzaSyA1nVLSPFs30wG-PLaEyFqm_PEVhZdzISU",
  authDomain: "geo-books-8411e.firebaseapp.com",
  projectId: "geo-books-8411e",
  storageBucket: "geo-books-8411e.firebasestorage.app",
  messagingSenderId: "972887107793",
  appId: "1:972887107793:web:7e0374bf81e6713fd0fdf0",
  measurementId: "G-RY84V5DXPN"
};

export const app = getApps().length ? getApps()[0] : initializeApp(firebaseConfig);
export const auth = getAuth(app);
export const db = getFirestore(app);

export const API_BASE_URL = window.GEO_BOOKS_API_URL ||
  (location.hostname === 'localhost' || location.hostname === '127.0.0.1' ? 'http://localhost:3007' : '');

export const escapeHTML = (v) =>
  String(v ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

/** Authenticated POST to server.js; throws Error(message) on failure. */
export async function apiPost(path, body) {
  const user = auth.currentUser;
  if (!user) throw new Error('You must be signed in.');
  const idToken = await user.getIdToken();
  const res = await fetch(`${API_BASE_URL}${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${idToken}` },
    body: JSON.stringify(body || {})
  });
  let data = null;
  try { data = await res.json(); } catch (e) { /* non-JSON error body */ }
  if (!res.ok) throw new Error((data && data.error) || `Server error (${res.status})`);
  return data;
}

// ---------------------------------------------------------------------------
// HTML safety. Lesson HTML is generated by AI and rendered with innerHTML, so
// it is re-sanitised here on every render against an allow-list of tags and
// the exact MedPhysio component class names (the server already did the same
// when generating — this is defence in depth, and also covers hand-edited HTML
// saved from the admin review step).
// ---------------------------------------------------------------------------
const ALLOWED_TAGS = new Set(['H3', 'H4', 'P', 'STRONG', 'EM', 'B', 'I', 'UL', 'OL', 'LI', 'DIV', 'SPAN', 'SMALL', 'BR', 'SUP', 'SUB']);
const ALLOWED_CLASSES = new Set([
  'mini-section-title', 'requirement-pills', 'cause-grid', 'morph-grid', 'function-list',
  'epo-flow', 'clinical-box', 'mini-summary', 'exam-summary'
]);

export function sanitizeLessonHtml(html) {
  const doc = new DOMParser().parseFromString(`<body>${String(html || '')}</body>`, 'text/html');
  const walk = (node) => {
    [...node.childNodes].forEach((child) => {
      if (child.nodeType === 3) return;                 // text
      if (child.nodeType !== 1) { child.remove(); return; } // comments etc.
      if (!ALLOWED_TAGS.has(child.tagName)) {
        // Drop dangerous elements entirely; unwrap harmless unknown ones.
        if (/^(SCRIPT|STYLE|IFRAME|OBJECT|EMBED|SVG|MATH|FORM|LINK|META|TEMPLATE)$/.test(child.tagName)) { child.remove(); return; }
        walk(child);
        child.replaceWith(...child.childNodes);
        return;
      }
      const keep = (child.getAttribute('class') || '').split(/\s+/).filter((c) => ALLOWED_CLASSES.has(c));
      [...child.attributes].forEach((a) => child.removeAttribute(a.name));
      if (keep.length) child.setAttribute('class', keep.join(' '));
      walk(child);
    });
  };
  walk(doc.body);
  return doc.body.innerHTML;
}

export const stripTags = (html) =>
  String(html || '').replace(/<[^>]*>/g, ' ').replace(/&nbsp;/g, ' ').replace(/\s+/g, ' ').trim();

export const estimateReadMinutes = (html) =>
  Math.max(1, Math.round(stripTags(html).split(/\s+/).filter(Boolean).length / 200));

// ---------------------------------------------------------------------------
// Link normalisers — same behaviour as MedPhysio's lib/links.js.
// ---------------------------------------------------------------------------
export function normalizeYouTube(input) {
  const url = String(input || '').trim();
  if (!url) return null;
  const patterns = [
    /youtu\.be\/([a-zA-Z0-9_-]{6,})/,
    /youtube(?:-nocookie)?\.com\/watch\?(?:.*&)?v=([a-zA-Z0-9_-]{6,})/,
    /youtube(?:-nocookie)?\.com\/embed\/([a-zA-Z0-9_-]{6,})/,
    /youtube(?:-nocookie)?\.com\/shorts\/([a-zA-Z0-9_-]{6,})/
  ];
  for (const re of patterns) {
    const m = url.match(re);
    if (m) return { id: m[1], url: `https://youtu.be/${m[1]}`, embedUrl: `https://www.youtube-nocookie.com/embed/${m[1]}?rel=0` };
  }
  return null;
}

export function normalizeDrive(input) {
  const m = String(input || '').trim().match(/drive\.google\.com\/file\/d\/([a-zA-Z0-9_-]+)/);
  if (!m) return null;
  return { url: `https://drive.google.com/file/d/${m[1]}/view?usp=sharing`, embedUrl: `https://drive.google.com/file/d/${m[1]}/preview` };
}

/** Only ever put https URLs into iframe/audio src attributes. */
export const safeHttpsUrl = (u) => (/^https:\/\/[^\s"'<>]+$/i.test(String(u || '')) ? String(u) : '');

// ---------------------------------------------------------------------------
// Data-model constants shared by admin + viewers
// ---------------------------------------------------------------------------
export const KIND = {
  uni: { collection: 'courseTopics', courseField: 'courseId', label: 'University' },
  tutor: { collection: 'tutorTopics', courseField: 'tutorCourseId', label: 'Tutor' }
};

export const PROGRESS_KEY_PREFIX = 'geoBooksLessonProgress:'; // same key lesson.htm uses

// ---------------------------------------------------------------------------
// Access + loading shared by subject.htm and subject-lesson.htm.
// This is UX only — firestore.rules (hasUniversityAccess / tutorPurchases) and
// server.js (/api/ai/subject-ask) enforce the same checks independently.
// ---------------------------------------------------------------------------
/** @returns {Promise<{ok:boolean, pending?:boolean, reason?:string}>} */
export async function checkSubjectAccess(user, kind, courseKey) {
  let isAdmin = false;
  try { isAdmin = (await user.getIdTokenResult()).claims.admin === true; } catch (e) { /* treat as non-admin */ }
  if (isAdmin) return { ok: true };

  if (kind === 'tutor') {
    try {
      const course = await getDoc(doc(db, 'tutorCourses', courseKey));
      if (course.exists() && course.data().tutorId === user.uid) return { ok: true };
      const purchase = await getDoc(doc(db, 'tutorPurchases', `${user.uid}_${courseKey}`));
      if (purchase.exists() && purchase.data().status === 'verified') return { ok: true };
      if (purchase.exists()) return { ok: false, pending: true, reason: 'Your enrollment is recorded and awaiting admin verification. Check back shortly.' };
    } catch (e) { console.error('Tutor access check failed:', e); }
    return { ok: false, reason: 'Enroll in this tutor course to view its lessons.' };
  }

  try {
    const snap = await getDoc(doc(db, 'users', user.uid));
    const sub = snap.exists() ? snap.data().subscription : null;
    if (sub && ['UNIVERSITY_PASS_30', 'UNIVERSITY_PASS_70'].includes(sub.tier) && sub.verified === true && sub.status === 'active') return { ok: true };
  } catch (e) { console.error('University access check failed:', e); }
  return { ok: false, reason: 'You need an active University Pass to view these lessons.' };
}

/** All topics of a course, ordered. Sorted client-side so no composite index is required. */
export async function loadCourseTopics(kind, courseKey) {
  const k = KIND[kind];
  const snap = await getDocs(query(collection(db, k.collection), where(k.courseField, '==', courseKey)));
  return snap.docs.map((d) => ({ id: d.id, ...d.data() }))
    .sort((a, b) => (Number(a.topicNumber) || 0) - (Number(b.topicNumber) || 0));
}

export function readProgress(uid, topicId) {
  try { return new Set(JSON.parse(localStorage.getItem(`${PROGRESS_KEY_PREFIX}${uid || ''}:${topicId}`) || '[]')); }
  catch (e) { return new Set(); }
}
export function writeProgress(uid, topicId, set) {
  try { localStorage.setItem(`${PROGRESS_KEY_PREFIX}${uid || ''}:${topicId}`, JSON.stringify([...set])); }
  catch (e) { console.warn('Could not save progress locally:', e); }
}

export const LESSON_TABS = ['mini', 'voice', 'full', 'answer', 'quiz'];
